name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: ./scripts/start-server.sh
    - run: ./scripts/prepare.sh
    - run: export KAFKA_BOOTSTRAP_SERVER=localhost:9092
    - run: nohup node producer-backend/producer.js > /dev/null 2>&1 & echo $! > prun.pid
    - run: nohup node consumer-backend/consumer.js > cout.log & echo $! > crun.pid
    - run: P=$(cat prun.pid)
    - run: C=$(cat crun.pid)
    - run: sleep 3
    - run: if [ -s cout.log ]; 
           then
             cat cout.log
           else
             echo "fail"
             exit 1;
           fi
    - run: ./scripts/stop-server.sh